Repository IUS-CS/project-bernie-s-mittens, pull requests merged in 2021-03, with the labels that each got.

#23 Adding first rendition of architecture.md to docs
  doc/architecture.md
Labels: documentation

#25 Added pages and users apps, models and forms for creating user profil…
  README.md
  src/ProVax/settings.py
  src/ProVax/urls.py
  src/pages/__init__.py
  src/pages/admin.py
  src/pages/apps.py
  src/pages/migrations/__init__.py
  src/pages/models.py
  src/pages/tests.py
  src/pages/views.py
  src/requirements
  src/templates/base.html
  src/templates/home.html
  src/templates/user/user_create.html
  src/templates/user/user_detail.html
  src/users/__init__.py
  src/users/admin.py
  src/users/apps.py
  src/users/forms.py
  src/users/migrations/0001_initial.py
  src/users/migrations/0002_auto_20210313_2129.py
  src/users/migrations/0003_auto_20210313_2131.py
  src/users/migrations/0004_auto_20210313_2135.py
  src/users/migrations/__init__.py
  src/users/models.py
  src/users/tests.py
  src/users/views.py
Labels: documentation, enhancement

#26 Design Patterns
  doc/designpatterns.md
Labels: documentation

#27 user create now saves a user in database that can be accessed at /user
  src/ProVax/urls.py
  src/templates/user/user_create.html
  src/users/forms.py
  src/users/models.py
  src/users/views.py
Labels: enhancement
