Repository IUS-CS/project-bernie-s-mittens, pull requests merged in 2021-02, with the labels that each got.

#1 Added AUTHORS.md file
  AUTHORS.md
Labels: documentation

#3 Mk doc dr edit author
  AUTHORS.txt
  doc/organization.md
Labels: documentation

#11 Created Django project and updated security settings
  src/ProVax/ProVax/__init__.py
  src/ProVax/ProVax/__pycache__/__init__.cpython-39.pyc
  src/ProVax/ProVax/__pycache__/settings.cpython-39.pyc
  src/ProVax/ProVax/__pycache__/urls.cpython-39.pyc
  src/ProVax/ProVax/__pycache__/wsgi.cpython-39.pyc
  src/ProVax/ProVax/asgi.py
  src/ProVax/ProVax/settings.py
  src/ProVax/ProVax/urls.py
  src/ProVax/ProVax/wsgi.py
  src/ProVax/db.sqlite3
  src/ProVax/manage.py
Labels: enhancement

#12 .gitignore
  .gitignore
  README.md
Labels: enhancement

#14 Edited README, commented out problematic security settings
  README.md
  src/ProVax/ProVax/settings.py
Labels: documentation, enhancement

#19 Updated README to include initial setup including virtualenv
  README.md
  requirements
Labels: documentation

#20 Sprint1 Ceremony
  doc/images/Prototype.png
  doc/images/env_shot.PNG
  doc/sprint1.md
Labels: documentation

#21 Created admin page and superusers
  src/ProVax/settings.py
  src/helloWorld/admin.py
  src/helloWorld/migrations/0001_initial.py
  src/helloWorld/models.py
Labels: enhancement
